return {
    flowey = function(cutscene, event)
        Game.world.music:stop()
        local dark = Rectangle(0, 0, 640, 480)
        dark:setColor(0, 0, 0)
		dark:setLayer(500)
        Game.world:addChild(dark)

        cutscene:wait(5)
        
        local flowey = Sprite("objects/flowey/rise", 320, 240)
        flowey:play(0.05, false)
        flowey:setScale(2)
        flowey:setOrigin(0.5, 1)
		flowey:setLayer(501)
        Game.world:addChild(flowey)

        cutscene:wait(2)
        flowey:setSprite("objects/flowey/plain")
        flowey:setOrigin(0.49, 1.03)
		
        cutscene:showNametag("Flowey")
        cutscene:text("[voice:flowey1]* Uh...[wait:5] Howdy.")
        cutscene:hideNametag()

        cutscene:wait(3)
        cutscene:showNametag("Flowey")
        flowey:setSprite("objects/flowey/side")
        cutscene:text("[voice:flowey1]* So, uh...")
        flowey:setSprite("objects/flowey/plain")
        cutscene:text("[voice:flowey1]* I just thought I'd let you know...")
        cutscene:text("[voice:flowey1]* You're using an outdated version of this engine to play this mod.")
        cutscene:text("[voice:flowey1]* You'll need version 0.8.0 in order to play it.")
        flowey:setSprite("objects/flowey/side")
        cutscene:text("[voice:flowey1]* With said version,[wait:5] being the source code for the engine.")
        flowey:setSprite("objects/flowey/nice")
        cutscene:text("[voice:flowey1]* But don't worry!")
        flowey:setSprite("objects/flowey/nicesideum")
        cutscene:text("[voice:flowey1]* It's VERY easy to set up!")
        flowey:setSprite("objects/flowey/niceside")
        cutscene:text("[voice:flowey1]* All you need to do is go to the Kristal Github page...")
        flowey:setSprite("objects/flowey/nice")
        cutscene:text("[voice:flowey1]* Click the green button,[wait:5] and then download it!")
        flowey:setSprite("objects/flowey/niceside")
        cutscene:text("[voice:flowey1]* And, of course,[wait:5] you'll also have to download LOVE2D...")
        flowey:setSprite("objects/flowey/nicesideum")
        cutscene:text("[voice:flowey1]* And unzip the file containing Kristal...\n[wait:5]* Blah, blah, blah...")
        flowey:setSprite("objects/flowey/sassy")
        cutscene:text("[voice:flowey1]* I'm SURE you can figure out the rest.")
        flowey:setSprite("objects/flowey/nice")
        cutscene:text("[voice:flowey1]* Welp.[wait:5]\n* That's all that your old pal Flowey has to say!")
        flowey:setSprite("objects/flowey/nicesideum")
        cutscene:text("[voice:flowey1]* In the meantime though...")
        flowey:setSprite("objects/flowey/sassy")
        cutscene:text("[voice:flowey1]* I'll just leave you with the dog.")
        flowey:setSprite("objects/flowey/wink")
        cutscene:text("[voice:flowey1]* See ya around,[wait:5] "..Game.save_name..".")
        flowey:setSprite("objects/flowey/nice")
        cutscene:hideNametag()

        cutscene:wait(2)
		
        if Game.save_name == "BLUE" then
            cutscene:showNametag("Flowey")
            flowey:setSprite("objects/flowey/plain")
            cutscene:text("[voice:flowey1]* Wait a second...")
            cutscene:text("[voice:flowey1]* Your name is...")
            flowey:setSprite("objects/flowey/nice")
            cutscene:text('[voice:flowey1]* "'..Game.save_name..'"?')
            cutscene:hideNametag()

            cutscene:wait(3)
            cutscene:showNametag("Flowey")
            flowey:setSprite("objects/flowey/nicesideum")
            cutscene:text("[voice:flowey1]* Y'know,[wait:5] I've been wondering...")
            flowey:setSprite("objects/flowey/plain")
            cutscene:text("[voice:flowey1]* Why exactly ARE you blue?")
            flowey:setSprite("objects/flowey/side")
            cutscene:text("[voice:flowey1]* Is it because you're sad?[wait:5]\n* Or pure?")
            flowey:setSprite("objects/flowey/sassy")
            cutscene:text("[voice:flowey1]* ...or is it because you've been working in a meth lab of some kind?")
            flowey:setSprite("objects/flowey/nicesideum")
            cutscene:text("[voice:flowey1]* Not saying that I would know, of course!")
            flowey:setSprite("objects/flowey/niceside")
            cutscene:text("[voice:flowey1]* After all...")
            flowey:setSprite("objects/flowey/nice")
            cutscene:text("[voice:flowey1]* I'm not some balding, middle-aged human who has his own drug business.")
            cutscene:hideNametag()
        elseif Game.save_name == "PLAGUEIS" then
            cutscene:showNametag("Flowey")
            flowey:setSprite("objects/flowey/plain")
            cutscene:text("[voice:flowey1]* Wait a second...")
            cutscene:text("[voice:flowey1]* Your name is...")
            flowey:setSprite("objects/flowey/nice")
            cutscene:text('[voice:flowey1]* "'..Game.save_name..'"?')
            cutscene:hideNametag()

            cutscene:wait(3)
            cutscene:showNametag("Flowey")
            flowey:setSprite("objects/flowey/nicesideum")
            cutscene:text("[voice:flowey1]* Y'know,[wait:5] I've actually heard a legend of someone who went by that name once...")
            flowey:setSprite("objects/flowey/plain")
            cutscene:text("[voice:flowey1]* It was said that he had the power to save the ones he loved from death.")
            flowey:setSprite("objects/flowey/side")
            cutscene:text("[voice:flowey1]* His life however,[wait:5] was cut short.")
            flowey:setSprite("objects/flowey/niceside")
            cutscene:text("[voice:flowey1]* When he taught his apprentice everything he knew...")
            flowey:setSprite("objects/flowey/nice")
            cutscene:text("[voice:flowey1]* His apprentice KILLED him in his sleep!")
            flowey:setSprite("objects/flowey/niceside")
            cutscene:text("[voice:flowey1]* Hee hee hee...[wait:5]\n* It's kind of ironic really.")
            flowey:setSprite("objects/flowey/nicesideum")
            cutscene:text("[voice:flowey1]* He had the power to save others...")
            flowey:setSprite("objects/flowey/evil")
            cutscene:text("[voice:flowey2][speed:0.6]* But he couldn't even use them to save his own SOUL.")
            cutscene:hideNametag()
            flowey:setSprite("objects/flowey/laugh")
			flowey:play(0.05)
            Assets.playSound("floweylaugh")
			cutscene:wait(4)
            flowey:setSprite("objects/flowey/grin")
            cutscene:showNametag("Flowey")
            cutscene:text("[voice:flowey2]* Hahaha!!\n[wait:5]* What an absolute IDIOT!")
			
            cutscene:hideNametag()
        end
        flowey:setSprite("objects/flowey/nice")
        cutscene:wait(5)
        cutscene:after(function() 
            Game.world:loadMap("misc/dogcheck") 
        end)
    end,
}