return {
    door = function(cutscene, event)
        cutscene:text("* It's a cracked wall.")
        if cutscene:getCharacter("susie") and cutscene:getCharacter("brandon") then
            cutscene:showNametag("Susie")
            cutscene:text("* ... A dead end?", "nervous_side", "susie")
            cutscene:text("* WAS THIS ALL FOR NOTHING!?!?!?!?", "teeth_b", "susie")
            cutscene:showNametag("Brandon")
            cutscene:text("* Hold on,[wait:5] Susie,[wait:5] you see how the wall is a bit cracked?", "neutral_side", "brandon")
            cutscene:showNametag("Susie")
            cutscene:text("* Uhhh,[wait:5] I think?", "suspicious", "susie")
            cutscene:showNametag("Brandon")
            cutscene:text("* What if we tried breaking through it?", "happy", "brandon")
            cutscene:text("* You'll use Rude Buster,[wait:5] and I'll use Gamma Beam.", "happy_b", "brandon")
            cutscene:showNametag("Susie")
            cutscene:text("* Heh,[wait:5] works for me.", "smile", "susie")
            cutscene:hideNametag()
            cutscene:wait(cutscene:fadeOut(1, {wait = false}))
            Assets.playSound("rudebuster_swing", 1, 1)
            Assets.playSound("rainbowbeam", 0.5, 1)
            cutscene:text("* Brandon and Susie both try breaking the wall down.")
            Game:setFlag("spamgolorneo_door", true)
            cutscene:wait(cutscene:fadeIn(1, {wait = false}))
            cutscene:showNametag("Susie")
            cutscene:text("* Hell yeah!", "smile", "susie")
            cutscene:showNametag("Brandon")
            cutscene:text("* Well,[wait:5] that's the way forward dealt with.", "happy_b", "brandon")
            if #Game.party >= 3 then
                cutscene:showNametag("Susie")
                cutscene:text("* Hey uh,[wait:5] you think the two of us should scout ahead?", "smirk", "susie")
                cutscene:text("* Just so the rest of the party can get help if we get trapped.", "nervous_side", "susie")
                cutscene:text("* We uh,[wait:5] DID just blow a hole in the wall.", "nervous", "susie")
                cutscene:showNametag("Brandon")
                cutscene:text("* Yeah,[wait:5] that sounds good.", "happy", "brandon")
                cutscene:text("* Alright guys,[wait:5] we'll be back soon.", "happy_side", "brandon")
                if cutscene:getCharacter("dess") then
                    cutscene:showNametag("Dess")
                    cutscene:text("* Ooooh are you guys going on a date together?", "condescending", "dess")
                    cutscene:showNametag("Brandon")
                    cutscene:text("* A-[wait:5]a w-what?", "blush", "brandon")
                    cutscene:showNametag("Susie")
                    cutscene:text("* IT IS NOT A DATE!", "teeth_b", "susie")
                    cutscene:text("* C'mon,[wait:5] let's just go already.", "teeth", "susie")
                end
                cutscene:hideNametag()
                cutscene:wait(cutscene:fadeIn(1, {wait = false}))
                for k,chara in ipairs(Game.party) do
                    Game:setFlag(chara.id .. "_party", false)
                end
                Game.party = {}
                Game:addPartyMember("brandon")
                Game:addPartyMember("susie")
                Game:setFlag("brandon_party", true)
                Game:setFlag("susie_party", true)
                Game.world:mapTransition("spamgolorneo_save", "north", "down")
            else
                cutscene:text("* C'mon Susie,[wait:5] let's go.", "happy_side", "brandon")
                cutscene:hideNametag()
                cutscene:wait(cutscene:fadeIn(1, {wait = false}))
                Game:removePartyMember("brandon")
                Game:addPartyMember("brandon", 1)
                Game.world:mapTransition("spamgolorneo_save", "north", "down")
            end
        elseif cutscene:getCharacter("susie") and not cutscene:getCharacter("brandon") then
            cutscene:showNametag("Susie")
            cutscene:text("* ... A dead end?", "nervous_side", "susie")
            cutscene:text("* WAS THIS ALL FOR NOTHING!?!?!?!?", "teeth_b", "susie")
            cutscene:text("* Ugh,[wait:5] there must be a way forward somehow...", "suspicious", "susie")
            cutscene:hideNametag()
        elseif cutscene:getCharacter("brandon") and not cutscene:getCharacter("susie") then
            cutscene:showNametag("Brandon")
            cutscene:text("* Aaaaaand that's a dead end.", "suspicious", "brandon")
            cutscene:text("* Well great,[wait:5] that's just lovely.", "dissapointed", "brandon")
            cutscene:text("* Actualy...", "neutral_side", "brandon")
            cutscene:text("* Maybe I could break this down with the help of someone?", "happy_side", "brandon")
            cutscene:text("* The wall does seem kinda cracked.", "happy", "brandon")
            cutscene:hideNametag()
        else
            cutscene:text("* Unfortunately,[wait:5] it doesn't seem like your party can break it.")
        end
    end,

    barrier = function(cutscene, event)
        local x = event.x + event.width/2
        local y = event.y + event.height/2
        local brandon = cutscene:getCharacter("brandon")
        local susie = cutscene:getCharacter("susie")
        cutscene:detachCamera()
        cutscene:detachFollowers()
        brandon:walkTo(x + 40, y + 90)
        susie:walkTo(x - 40, y + 90)
        cutscene:wait(1)
        cutscene:showNametag("Susie")
        cutscene:text("* Man,[wait:5] this place looks just like the basement of Queen's mansion...", "sus_nervous", "susie")
        cutscene:showNametag("Brandon")
        cutscene:text("* Yeah,[wait:5] hopefully there aren't any teacups of doom.", "neutral_side", "brandon")
        cutscene:showNametag("Susie")
        cutscene:text("* Teacups of what?", "surprise", "susie")
        cutscene:showNametag("Brandon")
        cutscene:text("* Ask Kris about it,[wait:5] they'll know.", "suspicious", "brandon")
        cutscene:showNametag("Susie")
        cutscene:text("* Alright...", "smirk", "susie")
        cutscene:hideNametag()
        Assets.playSound("screenshake")
        Game.world:shakeCamera(5)
        Game:setFlag("spamgolorneo_barrier", true)
        cutscene:wait(1)
        susie:setFacing("up")
        brandon:setFacing("up")
        cutscene:showNametag("Susie")
        cutscene:text("* ...", "surprise", "susie")
        cutscene:text("* Well uh,[wait:5] that's not good.", "surprise_frown", "susie")
        cutscene:text("* Looks like we need to find a way out of here.", "suspicious", "susie")
        cutscene:text("* Why the hell did we even listen to that Spamgolor guy?", "teeth_b", "susie")
        cutscene:text("* Ugh,[wait:5] whatever,[wait:5] I'm going on ahead!", "teeth", "susie")
        brandon:setFacing("down")
        Game:removePartyMember("susie")
        cutscene:hideNametag()
        susie:walkTo(x - 40, y + 200, 0.5)
        cutscene:wait(0.5)
        susie:walkTo(x + 600, y + 200, 2)
        cutscene:showNametag("Brandon")
        cutscene:text("* Wait,[wait:5] Susie!", "frown", "brandon")
        cutscene:text("* ...", "frown_side", "brandon")
        cutscene:text("* Guess I better catch up to her.", "frown", "brandon")
        cutscene:hideNametag()
        cutscene:wait(cutscene:attachCamera(1))
    end,

    susdoor = function(cutscene, event)
        cutscene:text("* Looks like Susie is behind this door.")
        cutscene:text("* You should go look for that NEO body.")
    end,

    body = function(cutscene, event)
        cutscene:text("* It's the body that Spamgolor tasked you with finding.")
        cutscene:showNametag("Brandon")
        cutscene:text("* Well,[wait:5] I sure as hell can't cary THAT.", "suspicious", "brandon")
        cutscene:text("* Maybe I should go get Susie?", "neutral_side", "brandon")
        cutscene:hideNametag()
        Game:setFlag("spamgolorneo_activate", true)
    end,

    intro = function(cutscene, event)
        local x = event.x + event.width/2
        local y = event.y + event.height/2
        local brandon = cutscene:getCharacter("brandon")
        local spamgolor = cutscene:getCharacter("spamgolorneo")
        Game.world.music:fade(0, 1)
        cutscene:detachCamera()
        brandon:walkTo(x - 20, y, 2)
        cutscene:wait(1)
        Assets.playSound("criticalswing")
        spamgolor:slideTo(x - 20, y, 1, "in-cubic")
        cutscene:wait(1)
        Assets.playSound("impact")
        spamgolor:shake(5)
        brandon:setSprite("battle/defeat")
        brandon.flip_x = true
        brandon:slideTo(x + 150, y, 1, "out-cubic")
        cutscene:wait(1.5)
        cutscene:showNametag("Brandon")
        cutscene:text("* W-what the...?", "shaded_b", "brandon")
        cutscene:hideNametag()
        brandon:setFacing("left")
        brandon:setSprite("walk")
        brandon:setAnimation("walk")
        brandon.flip_x = false
        brandon:shake(5)
        Assets.playSound("wing")
        cutscene:wait(1)
        Game.world.music:fade(1, 0)
        Game.world.music:play("spamgolor_neo_intro", 1, 1)
        cutscene:showNametag("Spamgolor NEO")
        cutscene:text("* WELL DONE,[wait:5] BRANDON.[wait:10]\n* [[You have truly earned your reputation as a hero.]]", "", "spamgolor")
        cutscene:text("* YOU AND THAT [[Pink Lizard]] WERE BOTH SO EASY TO FOOL.", "", "spamgolor")
        cutscene:text("* AND NOW,[wait:5] THANKS TO YOUR [[Property Damage]] I HAVE [[Becomed]] NEO.", "", "spamgolor")
        cutscene:text("* AND NOW,[wait:5] I CAN FINALLY SPEAK MY MIND.", "", "spamgolor")
        spamgolor:setAnimation("shaking")
        cutscene:text("* I KNOW EVERYTHING ABOUT YOU,[wait:5] BRANDON", "", "spamgolor")
        spamgolor:setAnimation("idle")
        cutscene:showNametag("Brandon")
        cutscene:text("* W-what...?", "shaded", "brandon")
        cutscene:showNametag("Spamgolor NEO")
        cutscene:text("* YOU'RE THE REASON I'M [[At rock bottom]]!![wait:10] IT'S ALL YOUR FAULT!", "", "spamgolor")
        cutscene:showNametag("Brandon")
        cutscene:text("* I-I don't...", "sad", "brandon")
        cutscene:text("* I-I'm sorry I...", "sad_b", "brandon")
        cutscene:showNametag("Spamgolor NEO")
        cutscene:text("* IT'S TOO LATE FOR [[Apology videos]] NOW!", "", "spamgolor")
        if Game:getPartyMember("brandon").love >= 5 then
            cutscene:text("* YOU'VE RUINED NOT ONLY MY [[Business]],[wait:5] BUT SO MANY OTHERS AS WELL.", "", "spamgolor")
            cutscene:text("* YOU THINK YOU'RE SOME KIND OF [[Big Shot]] WHO CAN DO WHATEVER THEY WANT?", "", "spamgolor")
            cutscene:showNametag("Brandon")
            cutscene:text("* I-I...", "shaded_sad", "brandon")
            cutscene:showNametag("Spamgolor NEO")
        end
        cutscene:text("* BUT ENOUGH [[Dialogue]],[wait:5] DON'T YOU SEE THESE [[Silly strings]] ON ME?!", "", "spamgolor")
        cutscene:text("* I'M STILL NOT FREE YET!!", "", "spamgolor")
        cutscene:text("* I NEED... SOMETHING ELSE NOW...", "", "spamgolor")
        cutscene:text("* THAT'S RIGHT,[wait:5] BRANDON.", "", "spamgolor")
        Game.world.music:pause()
        spamgolor:setAnimation("aim")
        cutscene:text("[noskip]* I NEED YOUR [[S O U L]]", "", "spamgolor")
        cutscene:hideNametag()
        Game.world.music:play("spamgolor_neo_intro", 1, 1.5)
        spamgolor:slideTo(x + 70, y, 3)
        brandon:walkTo(x + 240, y, 3, "left", "left")
        cutscene:wait(3)
    end
}