return {
    fun_fax = function(cutscene, event)

        local x = SCREEN_WIDTH/2
        local y = SCREEN_HEIGHT/2

        Game.world:spawnNPC("fun_fax", -210, 660)
        Game.world.music:fade(0, 0.25)
        local fun_fax = cutscene:getCharacter("fun_fax")

        Assets.playSound("mac_start")
        cutscene:slideTo(fun_fax, 310, 660, 0.8, "in-out-quint")
        if not Game:getFlag("met_fun_fax") then
            cutscene:wait(5)
            cutscene:text("* [speed:0.2]Mmmmm,[wait:20][speed:0.2]\nyes[speed:0.1]..........")
            fun_fax:setSprite("watching")
            cutscene:wait(3)
            fun_fax:setSprite("searching")
            cutscene:wait(2)
            fun_fax:setSprite("watching")
            cutscene:wait(1)
            fun_fax:setSprite("searching")
            cutscene:wait(0.5)
            fun_fax:setSprite("watching")
            cutscene:wait(0.5)
            fun_fax:setSprite("searching")
            cutscene:wait(0.5)
            fun_fax:setSprite("watching")
            cutscene:wait(0.5)
            fun_fax:setSprite("searching")
            cutscene:wait(0.25)
            fun_fax:setSprite("searching")
            cutscene:wait(0.12)
            fun_fax:setSprite("watching")
            cutscene:wait(0.05)
            fun_fax:setSprite("searching")
            cutscene:wait(0.05)
            fun_fax:setSprite("watching")
            cutscene:wait(0.05)
            fun_fax:setSprite("searching")
            cutscene:wait(0.05)
            fun_fax:setSprite("watching")
            cutscene:wait(0.05)
            fun_fax:setSprite("searching")
            cutscene:wait(0.005)
            fun_fax:setSprite("watching")
            cutscene:wait(0.0005)
            fun_fax:setSprite("searching")
            cutscene:wait(0.00005)
            fun_fax:setSprite("watching")
            cutscene:wait(0.000005)
            fun_fax:setSprite("searching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("watching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("searching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("watching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("searching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("watching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("searching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("watching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("searching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("watching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("searching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("watching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("searching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("watching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("searching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("watching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("searching")
            cutscene:wait(0.0000005)
            fun_fax:setSprite("searching")
            cutscene:wait(3)
            fun_fax:setSprite("watching")
            cutscene:wait(5)
            cutscene:text("* Alola...")
            cutscene:text("* [speed:0.5]That's a pokemon yaknow...[wait:25]\n...[wait:25]\n...")
            cutscene:text("* [speed:0.25]...[wait:25]\n...[wait:25]\n...")
            cutscene:text("* [speed:0.25]...[wait:25]\n...[wait:25]\n...")
            cutscene:wait(3)
            Game:setFlag("met_fun_fax", true)
        else
            cutscene:wait(4)
            fun_fax:setSprite("watching")
            cutscene:wait(1)
            fun_fax:setSprite("searching")
            cutscene:wait(0.5)
            fun_fax:setSprite("watching")
            cutscene:wait(0.25)
        end
        fun_fax:setSprite("searching")
        cutscene:wait(0.5)
        Assets.playSound("ui_select")
        cutscene:wait(0.1)
        local random_theme = Music(Mod:get_random_song(), 0.8, 1)
        cutscene:wait(0.4)
        fun_fax:setSprite("watching")
        cutscene:wait(2)
        cutscene:text(Mod:get_random_text())
        fun_fax:setSprite("searching")
        cutscene:wait(1.5)
        fun_fax:setSprite("watching")
        cutscene:wait(1.5)
        cutscene:text(Mod:get_random_text2())
        cutscene:wait(3)
        fun_fax:setSprite("searching")
        Assets.playSound("ui_select")
        random_theme:stop()
        cutscene:wait(0.2)
        fun_fax:setSprite("watching")
        cutscene:wait(2)
        cutscene:slideTo(fun_fax, 800, 660, 0.8, "in-out-quint")
        Assets.playSound("mac_start")
        cutscene:wait(0.2)
        fun_fax:setSprite("searching")
        cutscene:wait(2)
        fun_fax:remove()
        Game.world.music:fade(1, 0.5)
    end
}
