local mymap, super = Class(Map)

function mymap:init(world, data)
    super:init(self, world, data)

    Game.world.fader:fadeOut(0, {alpha = 0})
end

function mymap:onEnter()
    super.onEnter(self)
    Game.world:spawnObject(CloudsBG(0, 0), "objects_bg")
    Game.stage:setWeather("gilded_grove_ambient", false)

    if Game:getFlag("#seen_altar_intro", false) == false then
        if Game.world:hasCutscene() then Game.world.cutscene:endCutscene() end
        Game.world:startCutscene(function(cutscene)
            cutscene:fadeOut(0)
            cutscene:wait(0.5)
            local gerome = cutscene:getCharacter("gerome")
            local asriel = cutscene:getCharacter("asriel")
            local synthlave = cutscene:getCharacter("synthlave")
            cutscene:walkTo(Game.world.player, "camp_3")
            --cutscene:detachFollowers()
            cutscene:detachCamera()
            Game.world.camera:setPosition(640, 460)
            cutscene:wait(0.5)
            cutscene:fadeIn(1)
            cutscene:wait(3)
            cutscene:wait(cutscene:panToSpeed("camp_2", 1))
            cutscene:wait(1.5)
            cutscene:text("* Isn't it beautiful?", nil, nil, {top = true})
            cutscene:text("* The Geyser of Life.", nil, nil, {top = true})
            cutscene:wait(0.75)
            cutscene:text("* Yep![wait:10] Still,[wait:5] the floating islands give me the creeps.[wait:10]\n* Like, how do they float???", nil, nil, {top = true})
            cutscene:wait(0.75)
            cutscene:text("* Such are the wonders of this wonderful world.", nil, nil, {top = true})
            cutscene:text("* Even after the terrible calamity, civilization kept evolving...", nil, nil, {top = true})
            cutscene:text("* The Darkners of this reality are truly something.", nil, nil, {top = true})
            cutscene:wait(0.75)
            cutscene:text("* ...", nil, nil, {top = true})
            cutscene:wait(0.75)
            cutscene:text("* Wazzat?[wait:10] Oh,[wait:5] yeah,[wait:5] mechahat.[wait:10] Why're we in this stupid stone place thing again?", nil, nil, {top = true})
            cutscene:wait(0.75)
            cutscene:text("* That...[wait:10] Is not my name.", nil, nil, {top = true})
            cutscene:wait(0.75)
            cutscene:text("* Right right,[wait:10] does Mettaton sound better?", nil, nil, {top = true})
            cutscene:wait(0.75)
            cutscene:text("* No,[wait:5] that sounds worse actually.[wait:10] Like some sort of obscure reference,[wait:5] even.", nil, nil, {top = true})
            cutscene:text("* Also kindly shut the $&!% up and look at the Geyser.", nil, nil, {top = true})
            cutscene:text("* It is relevant to the plot,[wait:5] just trust me,[wait:5] dude.", nil, nil, {top = true})
            cutscene:wait(0.75)
            cutscene:look(asriel, "right")
            cutscene:wait(0.75)
            cutscene:text("* Listen,[wait:5] I'm actually confused now.", "huh", "asriel", {top = true})
            cutscene:text("* Is this REAL or this is a stupid dream???", "huh", "asriel", {top = true})
            cutscene:text("* All the psychological stuff and all the videogame terms are...", "narrow", "asriel", {top = true})
            cutscene:text("* ..... starting to make my brain rot.", "narrow", "asriel", {top = true})
            cutscene:text("* Not in a good way also.", "narrow_b", "asriel", {top = true})
            cutscene:wait(0.75)
            cutscene:look(synthlave, "left")
            cutscene:text("* I-[wait:10] Whuh-[wait:10] Huh???", "worried", "synthlave", {top = true})
            cutscene:text("* How In The Name of our Lord and Saviour Jesus Mother$&!%ing Christ", "question", "synthlave", {top = true})
            cutscene:text("* ... could your brain rotting possibly be a good thing???", "three_question", "synthlave", {top = true})
            cutscene:wait(0.75)
            cutscene:text("* Sigh,[wait:5] of course you don't get it...", "confident_c", "asriel", {top = true})
            cutscene:wait(0.75)
            cutscene:text("* Did You Just Say:[wait:10] \"Sigh\"[wait:10]\n* Quote unquote?", "silent", "synthlave", {top = true})
            cutscene:wait(0.75)
            cutscene:text("* Nah,[wait:5] you must've imagined it.[wait:10] Y'gotta get your ears checked,[wait:5] dude.", "smile", "asriel", {top = true})
            cutscene:wait(0.75)
            cutscene:text("* ...", "silent", "synthlave", {top = true})
            cutscene:wait(0.04)
            cutscene:text("* I am Starting to Think", "neutral", "synthlave", {top = true})
            cutscene:text("* It would have been better to leave you with those other two.", "neutral", "synthlave", {top = true})
            cutscene:wait(0.75)
            cutscene:text("* You don't say.", "confident_c", "asriel", {top = true})
            cutscene:wait(0.75)
            cutscene:text("* I Do Say,[wait:5] Actually", "angry", "synthlave", {top = true})
            cutscene:wait(1.25)
            cutscene:look(asriel, "up")
            cutscene:wait(1)
            cutscene:look(synthlave, "up")
            cutscene:wait(1.5)
            cutscene:attachCamera(5)
            Game:setFlag("#seen_altar_intro", true)
        end)
    end
end

return mymap