return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 14,
  nextobjectid = 70,
  properties = {
    ["music"] = "forest"
  },
  tilesets = {
    {
      name = "woods",
      firstgid = 1,
      filename = "../../tilesets/woods.tsx"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -20,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0, 0, 0,
        0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0,
        0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0,
        0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0,
        0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0,
        0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0,
        0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0,
        0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0,
        0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0,
        0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0,
        0, 0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 4,
      name = "Tile Layer 3",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 0, 40, 0, 41, 0, 0, 40, 0, 0, 0,
        0, 0, 0, 41, 0, 287, 289, 56, 37, 0, 0, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 287, 318, 316, 288, 288, 289, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 298, 299, 299, 299, 299, 305, 322, 37, 40, 0, 0, 0,
        0, 0, 0, 0, 309, 296, 299, 294, 310, 311, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 40, 309, 310, 311, 41, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 37, 0, 0, 0, 0, 0, 0, 2, 41, 0, 0, 0, 0,
        0, 0, 0, 0, 41, 0, 2, 0, 0, 40, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 37, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 9,
      name = "Tile Layer 4",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 345, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 368, 348, 0, 345, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 345, 367, 345, 367, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 346, 370, 346, 370, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 367, 0, 367, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 2,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -20,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 89, 90, 135, 90, 135, 90, 135, 90, 135, 90, 91, 0, 0,
        0, 188, 189, 190, 191, 146, 191, 146, 191, 146, 191, 146, 191, 192, 193, 194,
        0, 93, 94, 95, 202, 157, 202, 157, 202, 157, 202, 157, 202, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 100, 191, 192, 193, 194, 0, 0, 0, 0, 0, 188, 189, 190, 191, 102
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 40,
          width = 80,
          height = 440,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 440,
          width = 100,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 420,
          y = 440,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 40,
          width = 80,
          height = 440,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 40,
          width = 400,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "stonecollision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 240,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 280,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 280,
          width = 0,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 360,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 240,
          width = 0,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 240,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 160,
          width = 0,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 160,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 160,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 200,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 200,
          width = 0,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 280,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 320,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 360,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 240,
          width = 0,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 240,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 200,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 200,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 200,
          width = 0,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 280,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "blockcollision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 160,
          width = 80,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 160,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 200,
          width = 120,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 200,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 240,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 240,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 280,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 280,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 80,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 360,
          width = 120,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 320,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 320,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 200,
          width = 0,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 200,
          width = 40,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 160,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_buttons",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "tilebutton",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["blocks"] = false,
            ["cutscene"] = "common.pushblockreset",
            ["pressedsprite"] = "world/events/woodtile/pressed",
            ["sprite"] = "world/events/woodtile/idle"
          }
        },
        {
          id = 48,
          name = "tilebutton",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["blocks"] = true,
            ["cutscene"] = "bonus.act1_3",
            ["group"] = "buton",
            ["once"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "objects_tiles",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 7,
          name = "pushblock",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false
          }
        },
        {
          id = 49,
          name = "pushblock",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false,
            ["pressbuttons"] = false,
            ["sprite"] = "world/events/push_blocker"
          }
        },
        {
          id = 50,
          name = "pushblock",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false,
            ["pressbuttons"] = false,
            ["sprite"] = "world/events/push_blocker"
          }
        },
        {
          id = 51,
          name = "pushblock",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false,
            ["pressbuttons"] = false,
            ["sprite"] = "world/events/push_blocker"
          }
        },
        {
          id = 52,
          name = "pushblock",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false,
            ["pressbuttons"] = false,
            ["sprite"] = "world/events/push_blocker"
          }
        },
        {
          id = 53,
          name = "pushblock",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false,
            ["pressbuttons"] = false,
            ["sprite"] = "world/events/push_blocker"
          }
        },
        {
          id = 58,
          name = "stone",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false
          }
        },
        {
          id = 59,
          name = "stone",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false
          }
        },
        {
          id = 60,
          name = "stone",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false
          }
        },
        {
          id = 61,
          name = "pushblock",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false,
            ["pressbuttons"] = false,
            ["sprite"] = "world/events/push_blocker"
          }
        },
        {
          id = 62,
          name = "pushblock",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false,
            ["pressbuttons"] = false,
            ["sprite"] = "world/events/push_blocker"
          }
        },
        {
          id = 63,
          name = "stone",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["input_lock"] = false,
            ["inputlock"] = false,
            ["lock"] = false
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 56,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 465,
          width = 320,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "forest_12",
            ["marker"] = "fp6"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 57,
          name = "for12",
          type = "",
          shape = "point",
          x = 320,
          y = 440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 13,
      name = "Copy of Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -20,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 89, 90, 135, 90, 135, 90, 135, 90, 135, 90, 91, 0, 0,
        0, 188, 189, 190, 191, 146, 191, 146, 191, 146, 191, 146, 191, 192, 193, 194,
        0, 93, 94, 95, 114, 157, 114, 157, 114, 157, 114, 157, 114, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 93, 94, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95,
        0, 100, 191, 192, 193, 194, 0, 0, 0, 0, 0, 188, 189, 190, 191, 102
      }
    }
  }
}
