return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 22,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 8,
  nextobjectid = 35,
  properties = {
    ["border"] = "simple",
    ["music"] = "deltarune/wind_highplace"
  },
  tilesets = {
    {
      name = "thoughts",
      firstgid = 1,
      filename = "../../../../../../tilesets/thoughts.tsx",
      exportfilename = "../../../../../../tilesets/thoughts.lua"
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects_bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 22,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 4, 5, 5, 6, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 4, 5, 5, 6, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 2, 2, 5, 5, 5, 5, 2, 2, 3, 0, 0, 0,
        0, 0, 0, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        0, 0, 0, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        0, 0, 0, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        0, 0, 0, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        0, 0, 0, 7, 8, 8, 5, 5, 5, 5, 8, 8, 9, 0, 0, 0,
        0, 0, 0, 4, 5, 5, 4, 5, 5, 6, 5, 5, 6, 0, 0, 0,
        0, 0, 0, 4, 5, 5, 4, 5, 5, 6, 5, 5, 6, 0, 0, 0,
        0, 0, 0, 4, 5, 5, 4, 5, 5, 6, 5, 5, 6, 0, 0, 0,
        0, 0, 0, 4, 5, 5, 4, 5, 5, 6, 5, 5, 6, 0, 0, 0,
        0, 0, 0, 1, 2, 2, 5, 5, 5, 5, 2, 2, 3, 0, 0, 0,
        0, 0, 0, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        2, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        8, 8, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        5, 5, 5, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 0, 0, 0,
        5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0,
        5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects_glass",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 23,
          name = "magicalglass",
          class = "",
          shape = "rectangle",
          x = 520,
          y = 600,
          width = 120,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          class = "",
          shape = "rectangle",
          x = 200,
          y = 0,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 40,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 80,
          width = 40,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 320,
          width = 120,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          class = "",
          shape = "rectangle",
          x = 400,
          y = 320,
          width = 120,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 480,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 520,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 720,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 720,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 800,
          width = 400,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          class = "",
          shape = "rectangle",
          x = 520,
          y = 680,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          class = "",
          shape = "rectangle",
          x = 520,
          y = 480,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          class = "",
          shape = "rectangle",
          x = 560,
          y = 560,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          class = "",
          shape = "rectangle",
          x = 560,
          y = 680,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          class = "",
          shape = "rectangle",
          x = 520,
          y = 80,
          width = 40,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          class = "",
          shape = "rectangle",
          x = 440,
          y = 40,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          class = "",
          shape = "rectangle",
          x = 400,
          y = 0,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 24,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = -40,
          y = 560,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 240,
          y = -40,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "devhotel/rooms/room_001/thoughts/left3",
            ["marker"] = "north"
          }
        },
        {
          id = 26,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 640,
          y = 600,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "enemy",
          class = "",
          shape = "point",
          x = 320,
          y = 520,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "voidwanderer",
            ["chase"] = true,
            ["encounter"] = "2voidwanderer",
            ["group"] = "1",
            ["path"] = "1",
            ["progress"] = "0"
          }
        },
        {
          id = 33,
          name = "enemy",
          class = "",
          shape = "point",
          x = 320,
          y = 760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "voidwanderer",
            ["chase"] = true,
            ["encounter"] = "2voidwanderer",
            ["group"] = "1",
            ["path"] = "1",
            ["progress"] = "0.5"
          }
        },
        {
          id = 34,
          name = "script",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 160,
          width = 400,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "thoughts.susiespell",
            ["once"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 27,
          name = "north",
          class = "",
          shape = "point",
          x = 320,
          y = 40,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "spawn",
          class = "",
          shape = "point",
          x = 320,
          y = 120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "west",
          class = "",
          shape = "point",
          x = 40,
          y = 640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "east",
          class = "",
          shape = "point",
          x = 600,
          y = 640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "paths",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 31,
          name = "1",
          class = "",
          shape = "ellipse",
          x = 160,
          y = 520,
          width = 320,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
