return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 29,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 6,
  nextobjectid = 52,
  properties = {
    ["music"] = "mysterious_castle",
    ["name"] = "Castle Town?"
  },
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/objects/darktown.png",
      id = 3,
      name = "Image Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1120,
          width = 278,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 362,
          y = 1120,
          width = 278,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1055,
          width = 191,
          height = 106,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1055,
          width = 191,
          height = 106,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 830,
          width = 190,
          height = 130,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 830,
          width = 190,
          height = 130,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4,
          y = 400,
          width = 120,
          height = 480,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 516,
          y = 400,
          width = 120,
          height = 480,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "polygon",
          x = 124,
          y = 460,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = -40 },
            { x = 0, y = -40 }
          },
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "polygon",
          x = 516,
          y = 460,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -40, y = -40 },
            { x = 0, y = -40 }
          },
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 200,
          width = 164,
          height = 220,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 476,
          y = 200,
          width = 160,
          height = 220,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 236,
          y = 164,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 362,
          y = 164,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 236,
          y = 196,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 362,
          y = 194,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "polygon",
          x = 166,
          y = 286,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = -40 },
            { x = 0, y = -40 }
          },
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "polygon",
          x = 475,
          y = 286,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -40, y = -40 },
            { x = 0, y = -40 }
          },
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 182,
          y = 204,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 200,
          width = 24,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 396,
          y = 198,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 414,
          y = 202,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 424,
          y = 206,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 124,
          y = 578,
          width = 116,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 438,
          y = 582,
          width = 116,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 398,
          y = 738,
          width = 116,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 158,
          y = 702,
          width = 88,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 26,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "sprite",
          type = "",
          shape = "rectangle",
          x = 466,
          y = 876,
          width = 25,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["scalex"] = 2,
            ["scaley"] = 2,
            ["speed"] = 0.25,
            ["texture"] = "objects/torch/torch"
          }
        },
        {
          id = 30,
          name = "sprite",
          type = "",
          shape = "rectangle",
          x = 594,
          y = 876,
          width = 25,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["scalex"] = 2,
            ["scaley"] = 2,
            ["speed"] = 0.25,
            ["texture"] = "objects/torch/torch"
          }
        },
        {
          id = 31,
          name = "sprite",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 876,
          width = 25,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["scalex"] = 2,
            ["scaley"] = 2,
            ["speed"] = 0.25,
            ["texture"] = "objects/torch/torch"
          }
        },
        {
          id = 32,
          name = "sprite",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 876,
          width = 25,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["scalex"] = 2,
            ["scaley"] = 2,
            ["speed"] = 0.25,
            ["texture"] = "objects/torch/torch"
          }
        },
        {
          id = 33,
          name = "sprite",
          type = "",
          shape = "rectangle",
          x = 124,
          y = 458,
          width = 158,
          height = 166,
          rotation = 0,
          visible = true,
          properties = {
            ["scalex"] = 2,
            ["scaley"] = 2,
            ["texture"] = "objects/castle_building1"
          }
        },
        {
          id = 35,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 246,
          y = 192,
          width = 150,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "darktown_ribbit/castle_front",
            ["marker"] = "entry"
          }
        },
        {
          id = 40,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 630,
          y = 954,
          width = 20,
          height = 105,
          rotation = 0,
          visible = true,
          properties = {
            ["marker"] = "entry"
          }
        },
        {
          id = 42,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -10,
          y = 958,
          width = 20,
          height = 105,
          rotation = 0,
          visible = true,
          properties = {
            ["marker"] = "entry"
          }
        },
        {
          id = 43,
          name = "sprite",
          type = "",
          shape = "rectangle",
          x = 370,
          y = 460,
          width = 158,
          height = 166,
          rotation = 0,
          visible = true,
          properties = {
            ["scalex"] = 2,
            ["scaley"] = 2,
            ["texture"] = "objects/castle_building2"
          }
        },
        {
          id = 45,
          name = "sprite",
          type = "",
          shape = "rectangle",
          x = 366,
          y = 612,
          width = 158,
          height = 166,
          rotation = 0,
          visible = true,
          properties = {
            ["scalex"] = 2,
            ["scaley"] = 2,
            ["texture"] = "objects/castle_building3"
          }
        },
        {
          id = 47,
          name = "sprite",
          type = "",
          shape = "rectangle",
          x = 158,
          y = 702,
          width = 88,
          height = 76,
          rotation = 0,
          visible = true,
          properties = {
            ["scalex"] = 2,
            ["scaley"] = 2,
            ["texture"] = "objects/castle_computer"
          }
        },
        {
          id = 49,
          name = "stomper",
          type = "",
          shape = "rectangle",
          x = 495,
          y = 805,
          width = 48,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 1150,
          width = 80,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {
            ["marker"] = "entry"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 36,
          name = "spawn",
          type = "",
          shape = "point",
          x = 320,
          y = 392,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "entry",
          type = "",
          shape = "point",
          x = 320,
          y = 1120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "entry_right",
          type = "",
          shape = "point",
          x = 578,
          y = 982,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "entry_left",
          type = "",
          shape = "point",
          x = 24,
          y = 980,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "entry_castlefront",
          type = "",
          shape = "point",
          x = 320,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
