local Lib = {}

function Mod:get_random_text()
    local text = ({
        "* [speed:0.5]I wrote a book recently...",
        "* [speed:0.5]Mama always said life was like a box-o-chocolates...",
        "* [speed:0.5]Have you heard of the woody theory...",
        "* [speed:0.5]AcousticJamm once said...",
        "* [speed:0.5]Did you know sans is Ness...",
        "* [speed:0.5]Did you know Dess is Ness...",
        "* [speed:0.5]I can see your FUN value...",
        "* [speed:0.5]Don't forget...",
        "* [speed:0.5]You need to go fast...",
        "* [speed:0.5]It need to be in an infinity room...",
        "* [speed:0.5]The DEVS don't know they aren't the real ones...",
        "* [speed:0.5]DeltaDreams died for this...",
        "* [speed:0.5]I can see things far away...",
        "* [speed:0.5]Drink soda...",
        "* [speed:0.5]I had a wife...",
        "* [speed:0.5]I was created in a night...",
        "* [speed:0.5]This is a full quote in the code...",
        "* [speed:0.5]If it's not worth it...",
        "* [speed:0.5]Hunger strikes me...",
        "* [speed:0.5]The lore doesn't matter...",
        "* [speed:0.5]There is nobody behind the tree...",
        "* [speed:0.5]Time does not matter...",
        "* [speed:0.5]Do your choices matter...",
        "* [speed:0.5]What is a dark world...",
        "* [speed:0.5]Is there a light fountain...",
        "* [speed:0.5]Do you miss them...",
        "* [speed:0.5]Is it fate...",
        "* [speed:0.5]Gender is odd to me...",
        "* [speed:0.5]The end is never...",
        "* [speed:0.5]The line between fact and fiction can be blurred...",
    })[love.math.random(1, 30)]  -- fallback: "* Code broke D:"
    return text
end

function Mod:get_random_text2()
    local text = ({
        "* [speed:0.5]It had a few quotes...",
        "* [speed:0.5]Ya never know what ya might get...",
        "* [speed:0.5]It means there is a friend inside you...",
        "* [speed:0.5]Brb, I gotta iron my fish...",
        "* [speed:0.5]Game Theory told me so...",
        "* [speed:0.5]JaruJaruJ told me so...",
        "* [speed:0.5]I'm not allowed to tell you though...",
        "* [speed:0.5]I'm with you in the dark...",
        "* [speed:0.5]As fast as you can...",
        "* [speed:0.5]There stands a goner who could aid you on your quest...",
        "* [speed:0.5]Never tell them this information...",
        "* [speed:0.5]Not really...",
        "* [speed:0.5]I can't see you...",
        "* [speed:0.5]It'll help you see faster...",
        "* [speed:0.5]But they took her in the devorce...",
        "* [speed:0.5]Sleep deprivation is unhealthy...",
        "* [speed:0.5]It was just split into two...",
        "* [speed:0.5]You should not do it...",
        "* [speed:0.5]I must proceed...",
        "* [speed:0.5]Just enjoy the fun...",
        "* [speed:0.5]I checked...",
        "* [speed:0.5]It always ends...",
        "* [speed:0.5]It always depends...",
        "* [speed:0.5]A world in darkness...",
        "* [speed:0.5]I would not know...",
        "* [speed:0.5]You probably don't know who I'm talking about...",
        "* [speed:0.5]Or is it chance...",
        "* [speed:0.5]It keeps being updated...",
        "* [speed:0.5]Or so I was told...",
        "* [speed:0.5]Until it isn't there anymore...",
    })[love.math.random(1, 30)]  -- fallback: "* Code broke D:"
    return text
end

function Mod:get_random_song()
    local text = ({
        "deltarune/castletown_empty",
        "deltarune/field_of_hopes",
        "deltarune/lancer",
        "battle",
        "deltarune/forest",
        "deltarune/THE_HOLY",
        "deltarune/town",
        "deltarune/castletown",
        "deltarune/berdly_theme",
        "deltarune/cybercity",
        "deltarune/cybercity_alt",
        "deltarune/queen_car_radio",
        "deltarune/dogcheck",
        "castle_funk",
        "greenroom",
        "keygen_credits",
        "results",
        "baci_perugina2",
        "spamton_battle_eb",
        "battleut",
        "battle2ut",
        "dance_of_dog",
        "sigh_of_dog",
        "options_fall",
        "options_summer",
        "options_winter",
        "mus_star",
        "dogcheck_anniversary",
        "Hugs_for_Ralsei",
        "Lullaby_for_Lancer",
        "spamgolor",
        "spamgolor_battle",
        "spamgolor_shop",
        "spamgolor_neo",
        "exception",
        "warphub",
        "checkpoint",
        "cloudwebs",
        "ruins_beta",
        "cursedcathedral_cover",
        "tickroom",
        "gimmieyourwalletmiss",
        "batterup",
        "threestrikesyoureout",
        "beasts",
        "room_003",
        "battle_repainted",
        "morpho_boss",
        "mirati_bk70cover",
        "mari_neo",
    })[love.math.random(1, 50)]  -- fallback: "* Code broke D:"
    return text
end
return Lib
