return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 25,
  height = 30,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 11,
  nextobjectid = 141,
  properties = {
    ["border"] = "castle",
    ["music"] = "deltarune/bird",
    ["use_footstep_sounds"] = true
  },
  tilesets = {
    {
      name = "bg_darkfield_tiles",
      firstgid = 1,
      filename = "../../../tilesets/bg_darkfield_tiles.tsx",
      exportfilename = "../../../tilesets/bg_darkfield_tiles.lua"
    },
    {
      name = "treetiles_new",
      firstgid = 67,
      filename = "../../../tilesets/bg_treetiles_new.tsx",
      exportfilename = "../../../tilesets/bg_treetiles_new.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 25,
      height = 30,
      id = 1,
      name = "tiles",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 1, 1, 1, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 1, 1, 1, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 1, 1, 1, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 15, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 15, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 15, 1, 1, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0,
        0, 0, 0, 20, 21, 1, 1, 19, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 15, 1, 1, 1, 1, 1, 1, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 15, 1, 1, 1, 1, 1, 1, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 15, 1, 1, 1, 1, 1, 1, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 8, 9, 1, 1, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 15, 1, 1, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        0, 0, 0, 0, 15, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 15, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 1, 1, 7, 8, 8, 8, 8, 8, 8,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 21, 1, 1, 19, 20, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 1, 1, 1, 1, 1, 1, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 1, 1, 1, 1, 1, 1, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 1, 1, 1, 1, 1, 1, 13, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 9, 1, 1, 7, 8, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 1, 1, 13, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 1, 1, 13, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 1, 1, 13, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 1, 1, 13, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 1, 1, 13, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 0.5,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 83,
          name = "",
          class = "",
          shape = "rectangle",
          x = 800,
          y = 0,
          width = 40,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          class = "",
          shape = "rectangle",
          x = 200,
          y = 280,
          width = 440,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          class = "",
          shape = "rectangle",
          x = 640,
          y = 0,
          width = 40,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 320,
          width = 80,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          class = "",
          shape = "rectangle",
          x = 280,
          y = 400,
          width = 520,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          class = "",
          shape = "rectangle",
          x = 360,
          y = 480,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          class = "",
          shape = "rectangle",
          x = 280,
          y = 600,
          width = 720,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 600,
          width = 80,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          class = "",
          shape = "rectangle",
          x = 200,
          y = 760,
          width = 440,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 760,
          width = 280,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          class = "",
          shape = "rectangle",
          x = 800,
          y = 840,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 960,
          width = 80,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "",
          class = "",
          shape = "rectangle",
          x = 520,
          y = 840,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 480,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          class = "",
          shape = "rectangle",
          x = 560,
          y = 960,
          width = 80,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 87,
          name = "entrydown",
          class = "",
          shape = "point",
          x = 740,
          y = 260,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "entryup",
          class = "",
          shape = "point",
          x = 680,
          y = 1160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "spawn",
          class = "",
          shape = "point",
          x = 240,
          y = 560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["border"] = "castle",
            ["music"] = "deltarune/bird",
            ["name"] = "Field",
            ["use_footstep_sounds"] = true
          }
        },
        {
          id = 138,
          name = "entryleft",
          class = "",
          shape = "point",
          x = 950,
          y = 720,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 86,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 680,
          y = 160,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "cloudwebs/_ch1/fields_1",
            ["marker"] = "entryup"
          }
        },
        {
          id = 93,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 640,
          y = 1180,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "cloudwebs/_ch1/fields_3",
            ["marker"] = "entrydown"
          }
        },
        {
          id = 48,
          name = "",
          class = "",
          shape = "rectangle",
          x = 780,
          y = 202,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          class = "",
          shape = "rectangle",
          x = 480,
          y = 202,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          class = "",
          shape = "rectangle",
          x = 710,
          y = 76,
          width = 210,
          height = 136,
          rotation = 0,
          gid = 69,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          class = "",
          shape = "rectangle",
          x = 550,
          y = 76,
          width = 210,
          height = 136,
          rotation = 0,
          gid = 70,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          class = "",
          shape = "rectangle",
          x = 440,
          y = 320,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          class = "",
          shape = "rectangle",
          x = 40,
          y = 400,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          class = "",
          shape = "rectangle",
          x = -40,
          y = 520,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          class = "",
          shape = "rectangle",
          x = -40,
          y = 680,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          class = "",
          shape = "rectangle",
          x = 680,
          y = 520,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          class = "",
          shape = "rectangle",
          x = 480,
          y = 520,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          class = "",
          shape = "rectangle",
          x = 280,
          y = 520,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          class = "",
          shape = "rectangle",
          x = 280,
          y = 680,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          class = "",
          shape = "rectangle",
          x = 550,
          y = 680,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          class = "",
          shape = "rectangle",
          x = 800,
          y = 680,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          class = "",
          shape = "rectangle",
          x = 40,
          y = 800,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          class = "",
          shape = "rectangle",
          x = 800,
          y = 360,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 1120,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 1240,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          class = "",
          shape = "rectangle",
          x = 440,
          y = 1120,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          class = "",
          shape = "rectangle",
          x = 440,
          y = 1240,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          class = "",
          shape = "rectangle",
          x = 400,
          y = 880,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          class = "",
          shape = "rectangle",
          x = 200,
          y = 880,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          class = "",
          shape = "rectangle",
          x = 760,
          y = 880,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          class = "",
          shape = "rectangle",
          x = 800,
          y = 1000,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          class = "",
          shape = "rectangle",
          x = 360,
          y = 1000,
          width = 210,
          height = 182,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 980,
          y = 680,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "cloudwebs/_ch1/fields_2b",
            ["marker"] = "entry"
          }
        }
      }
    }
  }
}
